export enum LoginAttemptReason {
	SUCCESS = 'SUCCESS',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
	EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
	RATE_LIMITED = 'RATE_LIMITED',
}
